"""fix pet id autoincrement

Revision ID: 4acd0a2298ed
Revises: 1e7c9447ed8f
Create Date: 2025-12-18 23:34:56.649216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4acd0a2298ed'
down_revision = '1e7c9447ed8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_service', schema=None) as batch_op:
        batch_op.alter_column('id_service',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_service', schema=None) as batch_op:
        batch_op.alter_column('id_service',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
