"""подключили sequence к med_card

Revision ID: 5c8227afc715
Revises: 4acd0a2298ed
Create Date: 2025-12-21 23:43:14.759031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8227afc715'
down_revision = '4acd0a2298ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis_pet', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'diagnosis', ['id_diagnosis'], ['id_diagnosis'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis_pet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
