"""хэш паролей

Revision ID: a419d2b41f73
Revises: d7a6057f5532
Create Date: 2025-12-25 17:50:07.358858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a419d2b41f73'
down_revision = 'd7a6057f5532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['login'])

    batch_op.alter_column(
        'password_hash',
        type_=sa.Text,  # или sa.Text()
        existing_type=sa.String(),
        existing_nullable=False
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
