"""колонка даты записи

Revision ID: d7a6057f5532
Revises: 58c12173f65f
Create Date: 2025-12-23 03:59:52.148410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7a6057f5532'
down_revision = '58c12173f65f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_service', schema=None) as batch_op:
        batch_op.alter_column('date_service',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_service', schema=None) as batch_op:
        batch_op.alter_column('date_service',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    # ### end Alembic commands ###
